# 🏪 NovaMart Retail Sales Dataset Generator

## Business Objective

The objective of this project is to generate a realistic retail sales dataset for a fictional company called NovaMart.

## Project Workflow

1. Generate a realistic retail sales dataset
2. Clean and validate the data
3. Export the dataset to Excel
4. Perform SQL analysis
5. Conduct Exploratory Data Analysis (EDA)
6. Create visualizations using Matplotlib
7. Build interactive Power BI dashboards

## Dataset Information

Rows: 10,000

Columns:
- Order ID
- Customer ID
- Customer Name
- Product Name
- Category
- Quantity
- Sales
- Profit
- Discount
- State
- City
- Region
- Payment Method
- Salesperson
- Order Date

## Python Libraries Used

- Pandas
- NumPy
- Faker
- Random
- Datetime

# Step 1 - Import Libraries

In [1]:
import pandas as pd
import numpy as np
from faker import Faker
import random
from datetime import datetime, timedelta

fake = Faker ("en_IN")

print("Libraries imported succesfully")

Libraries imported succesfully

# Step 2 - Product Master

This section creates the product catalog.

Each product contains:

- Selling Price
- Cost Price

These values are later used to calculate sales, discounts and profit.

In [2]:
product_master = {
    "Electronics": {
        "Samsung Galaxy A56": (35000, 29000),
        "iPhone 16": (85000, 72000),
        "Dell Inspiron 15": (62000, 52000),
        "Lenovo ThinkPad": (78000, 66000),
        "iPad Air": (58000, 49000)
    },

    "Furniture": {
        "Office Chair": (6500, 4800),
        "Wooden Table": (12000, 9000),
        "Sofa Set": (45000, 36000),
        "Bookshelf": (8500, 6200),
        "Dining Table": (28000, 22000)
    },

    "Home Appliances": {
        "Mixer Grinder": (4200, 3100),
        "Ceiling Fan": (3200, 2500),
        "Refrigerator": (38000, 30000),
        "Washing Machine": (31000, 25000),
        "Microwave Oven": (14000, 11000)
    },

    "Clothing": {
        "Men's T-Shirt": (900, 500),
        "Women's Kurti": (1500, 850),
        "Jeans": (2200, 1400),
        "Jacket": (4200, 3000),
        "Sports Shoes": (3500, 2400)
    },

    "Grocery": {
        "Rice 10kg": (850, 650),
        "Milk": (65, 48),
        "Tea Powder": (420, 310),
        "Coffee": (520, 390),
        "Biscuits": (120, 80)
    },

    "Accessories": {
        "Boat Airdopes": (1800, 1200),
        "Noise Smartwatch": (3500, 2500),
        "Logitech Mouse": (900, 650),
        "HP Keyboard": (1100, 800),
        "Samsung Charger": (1200, 850)
    }
}

# Step 3 - City & State Mapping

In [3]:
cities = {
    "Chennai": "Tamil Nadu",
    "Madurai": "Tamil Nadu",
    "Coimbatore": "Tamil Nadu",
    "Bangalore": "Karnataka",
    "Mysore": "Karnataka",
    "Hyderabad": "Telangana",
    "Vijayawada": "Andhra Pradesh",
    "Kochi": "Kerala",
    "Thiruvananthapuram": "Kerala",
    "Pune": "Maharashtra"
}

# Step 3A - Payment Methods

In [4]:
payment_methods = [
    "UPI",
    "Credit Card",
    "Debit Card",
    "Cash",
    "Net Banking"
]

# Step 3B - Salespersons

In [5]:
salespersons = [
    "Rahul Sharma",
    "Priyanka",
    "Arjun Kumar",
    "Sneha Reddy",
    "Vikram Singh",
    "Ananya pandya",
    "Rohan Patel",
    "Divya dharshini",
    "hrithik anand",
    "Arsheya begum"
]

# Step 4 - Generate Customer Master

This section generates 6000 synthetic customers.

The customer master is later used to simulate repeat purchases.

In [6]:
customers = []

for i in range(1,6001):

    city = random.choice(list(cities.keys()))
    state = cities[city]

    customers.append({
        "customer_id": f"CUST{i:04}",
        "customer_name": fake.name(),
        "city": city,
        "state": state
    })

customer_master = pd.DataFrame(customers)

customer_master.head()

  customer_id   customer_name       city        state
0    CUST0001    Nitara Saran  Bangalore    Karnataka
1    CUST0002     Nakul Baral       Pune  Maharashtra
2    CUST0003  Gautam Sampath      Kochi       Kerala
3    CUST0004       Frado Vig  Hyderabad    Telangana
4    CUST0005     Leela Tella  Bangalore    Karnataka

# Step 5 - Generate Transaction Function

This function generates one complete retail transaction.

Each transaction contains:

- Customer
- Product
- Quantity
- Sales
- Profit
- Payment Method
- Region

In [7]:
def generate_transaction(order_number):

    # Select a random product category
    category = random.choice(list(product_master.keys()))
    product = random.choice(list(product_master[category].keys()))
    selling_price, cost_price = product_master[category][product]

    # Order
    order_id = f"ORD{order_number:06d}"

    customer = customer_master.sample(1).iloc[0]

    customer_id = customer["customer_id"]

    customer_name = customer["customer_name"]

    city = customer["city"]

    state = customer["state"]
    
    region_mapping = {
    "Tamil Nadu": "South",
    "Karnataka": "South",
    "Kerala": "South",
    "Telangana": "South",
    "Andhra Pradesh": "South",

    "Maharashtra": "West",
    "Gujarat": "West",
    "Rajasthan": "West",
    "Goa": "West",

    "Delhi": "North",
    "Punjab": "North",
    "Haryana": "North",
    "Uttar Pradesh": "North",

    "West Bengal": "East",
    "Odisha": "East",
    "Bihar": "East",
    "Jharkhand": "East",
    "Assam": "East"
}

    region = region_mapping[state]

    # Date
    start_date = datetime(2025,1,1)
    end_date = datetime(2025,12,31)

    random_days = random.randint(0,(end_date-start_date).days)
    order_date = start_date + timedelta(days=random_days)

    # Sales Details
    quantity = random.randint(1,5)

    discount = random.choice([0,5,10,15,20])

    sales = selling_price * quantity

    discount_amount = sales * discount / 100

    final_sales = sales - discount_amount

    cost = cost_price * quantity

    # Calculate profit
    profit = final_sales - cost

    # Payment & Salesperson
    payment_method = random.choices(
        payment_methods,
        weights=[45,20,15,10,10],
        k=1
    )[0]

    salesperson = random.choice(salespersons)

    # Return one transaction
    return {
        "order_id": order_id,
        "order_date": order_date.strftime("%Y-%m-%d"),
        "customer_id": customer_id,
        "customer_name": customer_name,
        "city": city,
        "state": state,
        "region": region,
        "category": category,
        "product_name": product,
        "quantity": quantity,
        "unit_price": selling_price,
        "discount_percent": discount,
        "sales": round(final_sales,2),
        "cost": cost,
        "profit": round(profit,2),
        "payment_method": payment_method,
        "salesperson": salesperson
    }

# Step 6 - Test the Function

## Verify Function Output

Before generating the complete dataset, we first test the function with a small sample of 10 transactions.

This helps verify that the business logic, calculations and data structure are working correctly.

In [8]:
transaction = generate_transaction(1)

In [9]:
transactions = []

for i in range(10):
    transactions.append(generate_transaction(i))

df = pd.DataFrame(transactions)
df["order_date"] = pd.to_datetime(df["order_date"])

df

,order_id,order_date,customer_id,customer_name,city,state,region,category,product_name,quantity,unit_price,discount_percent,sales,cost,profit,payment_method,salesperson
0,ORD000000,2025-10-15,CUST3996,Raksha Divan,Mysore,Karnataka,South,Furniture,Bookshelf,1,8500,0,8500.0,6200,2300.0,UPI,Divya dharshini
1,ORD000001,2025-04-19,CUST4753,Lakshit More,Thiruvananthapuram,Kerala,South,Clothing,Sports Shoes,2,3500,20,5600.0,4800,800.0,UPI,hrithik anand
2,ORD000002,2025-09-24,CUST4882,Yatin Sani,Thiruvananthapuram,Kerala,South,Grocery,Coffee,2,520,15,884.0,780,104.0,UPI,Divya dharshini
3,ORD000003,2025-06-23,CUST0489,Ayush Kaur,Hyderabad,Telangana,South,Home Appliances,Mixer Grinder,2,4200,5,7980.0,6200,1780.0,UPI,Divya dharshini
4,ORD000004,2025-01-27,CUST3280,Gaurang Chandran,Chennai,Tamil Nadu,South,Accessories,HP Keyboard,1,1100,0,1100.0,800,300.0,UPI,Arsheya begum
5,ORD000005,2025-05-25,CUST4440,Abeer Tella,Vijayawada,Andhra Pradesh,South,Clothing,Sports Shoes,1,3500,15,2975.0,2400,575.0,Debit Card,Rohan Patel
6,ORD000006,2025-08-27,CUST5225,Harini Kaul,Thiruvananthapuram,Kerala,South,Clothing,Men's T-Shirt,4,900,15,3060.0,2000,1060.0,Credit Card,hrithik anand
7,ORD000007,2025-10-31,CUST1106,Indali Cherian,Chennai,Tamil Nadu,South,Furniture,Bookshelf,5,8500,20,34000.0,31000,3000.0,Cash,Rohan Patel
8,ORD000008,2025-03-27,CUST2140,Radhika Nagar,Hyderabad,Telangana,South,Electronics,Dell Inspiron 15,4,62000,10,223200.0,208000,15200.0,Cash,Vikram Singh
9,ORD000009,2025-12-03,CUST2190,Upadhriti Wali,Hyderabad,Telangana,South,Electronics,Lenovo ThinkPad,2,78000,0,156000.0,132000,24000.0,Cash,Divya dharshini

# Step 7 - Generate Final Dataset

In [10]:
transactions = []

for i in range(1, 10001):
    transactions.append(generate_transaction(i))

df = pd.DataFrame(transactions)
df["order_date"] = pd.to_datetime(df["order_date"])

# Step 8 - Validate Generated Dataset

The following validation checks ensure that the generated dataset is complete, consistent, and ready for analysis.

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 17 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   order_id          10000 non-null  object
 1   order_date        10000 non-null  datetime64[ns]
 2   customer_id       10000 non-null  object
 3   customer_name     10000 non-null  object
 4   city              10000 non-null  object
 5   state             10000 non-null  object
 6   region            10000 non-null  object
 7   category          10000 non-null  object
 8   product_name      10000 non-null  object
 9   quantity          10000 non-null  int64
 10  unit_price        10000 non-null  int64
 11  discount_percent  10000 non-null  int64
 12  sales             10000 non-null  float64
 13  cost              10000 non-null  int64
 14  profit            10000 non-null  float64
 15  payment_method    10000 non-null  object
 16  salesperson       10000 non-null  object
dtypes: datetime64[ns](1), float64(2), int64(4), object(10)
memory usage: 1.3+ MB

In [12]:
df.isnull().sum()

order_id            0
order_date          0
customer_id         0
customer_name       0
city                0
state               0
region              0
category            0
product_name        0
quantity            0
unit_price          0
discount_percent    0
sales               0
cost                0
profit              0
payment_method      0
salesperson         0
dtype: int64

In [13]:
df.describe()

,order_date,quantity,unit_price,discount_percent,sales,cost,profit
count,10000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000
mean,2025-07-03 03:13:23.520000,2.999900,18020.755000,9.996000,48989.004025,44413.924000,4575.080025
min,2025-01-01 00:00:00,1.000000,65.000000,0.000000,52.000000,48.000000,-20000.000000
25%,2025-04-03 00:00:00,2.000000,1100.000000,5.000000,2800.000000,2000.000000,355.000000
50%,2025-07-03 00:00:00,3.000000,4200.000000,10.000000,10500.000000,9000.000000,1300.000000
75%,2025-10-03 00:00:00,4.000000,31000.000000,15.000000,61100.000000,55000.000000,4500.000000
max,2025-12-31 00:00:00,5.000000,85000.000000,20.000000,425000.000000,360000.000000,65000.000000
std,NaN,1.404171,24785.595985,7.105634,78218.512494,72708.656309,9119.797449

In [14]:
df.duplicated().sum()

np.int64(0)

# Step 9 - Export Dataset

In [16]:
# Export the final dataset to CSV

df.to_csv(
    "novamart_sales_dataset.csv",
    index=False
)

print("Dataset exported successfully!")

Dataset exported successfully!

# ✅ Project Completed

Dataset Name

**novamart_sales_dataset.csv**

Number of Transactions

**10,000**

This dataset will be used in:

- SQL Analysis
- Power BI Dashboard
- Python EDA
- Business Intelligence Portfolio

Status

✔ Dataset Successfully Generated